version: '3'

services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 3000:3001
  backend:
    build:
      dockerfile: backend.Dockerfile
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo

volumes:
  postgres-data:
