version: '3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 3001:3000
    depends_on:
      backend:
        condition: service_healthy
  backend:
    container_name: backend
    build:
      dockerfile: backend.Dockerfile
    ports:
      - 4001:4002
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4002/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo

volumes:
  postgres-data:
