version: '3'

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 3001:3000
  backend:
    container_name: backend
    build:
      dockerfile: backend.Dockerfile
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo

volumes:
  postgres-data:
